### ISSUE TITLE
java.lang.ClassNotFoundException: org.msgpack.template.Template

### ISSUE THREAD

**Issue by Lewuathe** [msgpack-rpc/msgpack-rpc#75]
Hi, I develop Jenkins plugin using msgpack. But in this time, an error has been occured in msgpack. Below debug log is printed when I do `mvn hpi:run`. When I do `mvn package`, unit test code using msgpack runs normally. 

```
INFO: Jenkins is fully up and running
Nov 24, 2013 11:08:22 PM hudson.model.Run execute
INFO: Test.COMMIT #25 main build action completed: SUCCESS
Nov 24, 2013 11:08:23 PM org.msgpack.template.builder.BuildContext build
SEVERE: builder: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  us.jubat.classifier.EstimateResult _$$_t;
  if ($2 == null) {
    _$$_t = new us.jubat.classifier.EstimateResult();
  } else {
    _$$_t = (us.jubat.classifier.EstimateResult) $2;
  }
  $1.readArrayBegin();
  if ($1.trySkipNil()) {  } else {
    _$$_t.label = (java.lang.String) this.templates[0].read($1, _$$_t.label);
  }
    _$$_t.score = $1.readDouble();
  $1.readArrayEnd();
  return _$$_t;
}

org.msgpack.MessageTypeException: org.msgpack.template.builder.TemplateBuildException: Cannot compile: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  us.jubat.classifier.EstimateResult _$$_t;
  if ($2 == null) {
    _$$_t = new us.jubat.classifier.EstimateResult();
  } else {
    _$$_t = (us.jubat.classifier.EstimateResult) $2;
  }
  $1.readArrayBegin();
  if ($1.trySkipNil()) {  } else {
    _$$_t.label = (java.lang.String) this.templates[0].read($1, _$$_t.label);
  }
    _$$_t.score = $1.readDouble();
  $1.readArrayEnd();
  return _$$_t;
}

    at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:516)
    at org.msgpack.template.TemplateRegistry.lookupAfterBuilding(TemplateRegistry.java:413)
    at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:246)
    at org.msgpack.template.TemplateRegistry.lookupGenericTypeImpl(TemplateRegistry.java:302)
    at org.msgpack.template.TemplateRegistry.lookupGenericType(TemplateRegistry.java:275)
    at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:201)
    at org.msgpack.template.TemplateRegistry.lookupGenericTypeImpl(TemplateRegistry.java:302)
    at org.msgpack.template.TemplateRegistry.lookupGenericType(TemplateRegistry.java:275)
    at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:201)
    at org.msgpack.MessagePack.lookup(MessagePack.java:624)
    at org.msgpack.rpc.reflect.ReflectionProxyBuilder.buildProxy(ReflectionProxyBuilder.java:156)
    at org.msgpack.rpc.reflect.ProxyBuilder.buildProxy(ProxyBuilder.java:72)
    at org.msgpack.rpc.reflect.Reflect.getProxy(Reflect.java:57)
    at org.msgpack.rpc.Session.proxy(Session.java:61)
    at us.jubat.common.ClientBase.<init>(ClientBase.java:33)
    at us.jubat.classifier.ClassifierClient.<init>(ClassifierClient.java:18)
    at com.lewuathe.plugins.jenkinsjubatus.JubatusClient.<init>(JubatusClient.java:22)
    at com.lewuathe.plugins.jenkinsjubatus.JubatusResultPublisher.perform(JubatusResultPublisher.java:51)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:780)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:752)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:705)
    at hudson.model.Run.execute(Run.java:1617)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:237)
Caused by: org.msgpack.template.builder.TemplateBuildException: Cannot compile: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  us.jubat.classifier.EstimateResult _$$_t;
  if ($2 == null) {
    _$$_t = new us.jubat.classifier.EstimateResult();
  } else {
    _$$_t = (us.jubat.classifier.EstimateResult) $2;
  }
  $1.readArrayBegin();
  if ($1.trySkipNil()) {  } else {
    _$$_t.label = (java.lang.String) this.templates[0].read($1, _$$_t.label);
  }
    _$$_t.score = $1.readDouble();
  $1.readArrayEnd();
  return _$$_t;
}

    at org.msgpack.template.builder.BuildContext.build(BuildContext.java:73)
    at org.msgpack.template.builder.DefaultBuildContext.buildTemplate(DefaultBuildContext.java:56)
    at org.msgpack.template.builder.JavassistTemplateBuilder.buildTemplate(JavassistTemplateBuilder.java:118)
    at org.msgpack.template.builder.AbstractTemplateBuilder.buildTemplate(AbstractTemplateBuilder.java:61)
    at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:503)
    ... 26 more
Caused by: javassist.CannotCompileException: by java.lang.NoClassDefFoundError: org/msgpack/template/Template
    at javassist.ClassPool.toClass(ClassPool.java:1099)
    at javassist.CtClass.toClass(CtClass.java:1181)
    at org.msgpack.template.builder.BuildContext.createClass(BuildContext.java:154)
    at org.msgpack.template.builder.BuildContext.build(BuildContext.java:68)
    ... 30 more
Caused by: java.lang.NoClassDefFoundError: org/msgpack/template/Template
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at javassist.ClassPool.toClass2(ClassPool.java:1112)
    at javassist.ClassPool.toClass(ClassPool.java:1093)
    ... 33 more
Caused by: java.lang.ClassNotFoundException: org.msgpack.template.Template
    at org.jenkinsci.maven.plugins.hpi.ServletApiOnlyClassLoader.findClass(ServletApiOnlyClassLoader.java:25)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:363)
    at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:325)
    ... 42 more
org.msgpack.MessageTypeException: org.msgpack.template.builder.TemplateBuildException: Cannot compile: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  us.jubat.classifier.EstimateResult _$$_t;
  if ($2 == null) {
    _$$_t = new us.jubat.classifier.EstimateResult();
  } else {
    _$$_t = (us.jubat.classifier.EstimateResult) $2;
  }
  $1.readArrayBegin();
  if ($1.trySkipNil()) {  } else {
    _$$_t.label = (java.lang.String) this.templates[0].read($1, _$$_t.label);
  }
    _$$_t.score = $1.readDouble();
  $1.readArrayEnd();
  return _$$_t;
}

    at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:516)
    at org.msgpack.template.TemplateRegistry.lookupAfterBuilding(TemplateRegistry.java:413)
    at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:246)
    at org.msgpack.template.TemplateRegistry.lookupGenericTypeImpl(TemplateRegistry.java:302)
    at org.msgpack.template.TemplateRegistry.lookupGenericType(TemplateRegistry.java:275)
    at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:201)
    at org.msgpack.template.TemplateRegistry.lookupGenericTypeImpl(TemplateRegistry.java:302)
    at org.msgpack.template.TemplateRegistry.lookupGenericType(TemplateRegistry.java:275)
    at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:201)
    at org.msgpack.MessagePack.lookup(MessagePack.java:624)
    at org.msgpack.rpc.reflect.ReflectionProxyBuilder.buildProxy(ReflectionProxyBuilder.java:156)
    at org.msgpack.rpc.reflect.ProxyBuilder.buildProxy(ProxyBuilder.java:72)
    at org.msgpack.rpc.reflect.Reflect.getProxy(Reflect.java:57)
    at org.msgpack.rpc.Session.proxy(Session.java:61)
    at us.jubat.common.ClientBase.<init>(ClientBase.java:33)
    at us.jubat.classifier.ClassifierClient.<init>(ClassifierClient.java:18)
    at com.lewuathe.plugins.jenkinsjubatus.JubatusClient.<init>(JubatusClient.java:22)
    at com.lewuathe.plugins.jenkinsjubatus.JubatusResultPublisher.perform(JubatusResultPublisher.java:51)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:780)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:752)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:705)
    at hudson.model.Run.execute(Run.java:1617)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:237)
Caused by: org.msgpack.template.builder.TemplateBuildException: Cannot compile: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  us.jubat.classifier.EstimateResult _$$_t;
  if ($2 == null) {
    _$$_t = new us.jubat.classifier.EstimateResult();
  } else {
    _$$_t = (us.jubat.classifier.EstimateResult) $2;
  }
  $1.readArrayBegin();
  if ($1.trySkipNil()) {  } else {
    _$$_t.label = (java.lang.String) this.templates[0].read($1, _$$_t.label);
  }
    _$$_t.score = $1.readDouble();
  $1.readArrayEnd();
  return _$$_t;
}

    at org.msgpack.template.builder.BuildContext.build(BuildContext.java:73)
    at org.msgpack.template.builder.DefaultBuildContext.buildTemplate(DefaultBuildContext.java:56)
    at org.msgpack.template.builder.JavassistTemplateBuilder.buildTemplate(JavassistTemplateBuilder.java:118)
    at org.msgpack.template.builder.AbstractTemplateBuilder.buildTemplate(AbstractTemplateBuilder.java:61)
    at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:503)
    ... 26 more
Caused by: javassist.CannotCompileException: by java.lang.NoClassDefFoundError: org/msgpack/template/Template
    at javassist.ClassPool.toClass(ClassPool.java:1099)
    at javassist.CtClass.toClass(CtClass.java:1181)
    at org.msgpack.template.builder.BuildContext.createClass(BuildContext.java:154)
    at org.msgpack.template.builder.BuildContext.build(BuildContext.java:68)
    ... 30 more
Caused by: java.lang.NoClassDefFoundError: org/msgpack/template/Template
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at javassist.ClassPool.toClass2(ClassPool.java:1112)
    at javassist.ClassPool.toClass(ClassPool.java:1093)
    ... 33 more
Caused by: java.lang.ClassNotFoundException: org.msgpack.template.Template
    at org.jenkinsci.maven.plugins.hpi.ServletApiOnlyClassLoader.findClass(ServletApiOnlyClassLoader.java:25)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:363)
    at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:325)
    ... 42 more
```

Are there any packages that is needed? My pom file is below.
I am terribly sorry to bother you, but I want some advice what to do.
My machine is OSX mavericks and I use maven-3.0.5. 
Thank you.

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.jenkins-ci.plugins</groupId>
    <artifactId>plugin</artifactId>
    <version>1.509.4</version><!-- which version of Jenkins is this plugin built against? -->
  </parent>

  <groupId>com.lewuathe.plugins</groupId>
  <artifactId>jenkins-jubatus</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>hpi</packaging>

  <!-- get every artifact through repo.jenkins-ci.org, which proxies all the artifacts that we need -->
  <repositories>
    <repository>
      <id>repo.jenkins-ci.org</id>
      <url>http://repo.jenkins-ci.org/public/</url>
    </repository>

        <repository>
      <id>jubat.us</id>
      <name>Jubatus Repository for Maven</name>
      <url>http://download.jubat.us/maven</url>
        </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>repo.jenkins-ci.org</id>
      <url>http://repo.jenkins-ci.org/public/</url>
    </pluginRepository>
  </pluginRepositories>

  <dependencies>
        <dependency>
      <groupId>us.jubat</groupId>
      <artifactId>jubatus</artifactId>
      <version>0.5.0</version>
        </dependency>
  </dependencies>

</project>
```

**Comment by olivergondza** [comment]
This looks like Jenkins problem [JENKINS-26579](https://issues.jenkins-ci.org/browse/JENKINS-26579).
